chore: fix cbuild on windows by reverting obsolete npm-path workaround (#2272)
#### Details

This PR reverts a Lerna workaround @pownkel added in #2009 which became
obsolete with our removal of Lerna in #2210. The workaround was breaking
the ability to run `yarn cbuild` on Windows machines - this PR restores
that capability.

##### Motivation

The upgrade to yarn 3 in #2210 accidentally broke all run scripts which
transitively refer to a `npm-run-all` command in non-WSL Windows
developer environments. Notably, this breaks `yarn cbuild` from the root
of the repo.

This manifested as a failing `yarn cbuild` command with output like
this:

<details>
<summary>full example output snippet</summary>
```
➤ YN0000: [parallel-workers]: Process started
➤ YN0000: [scanner-global-library]: Process started
➤ YN0000: [parallel-workers]:
➤ YN0000: [parallel-workers]: > parallel-workers@1.0.0 clean
➤ YN0000: [parallel-workers]: > rimraf dist test-results
➤ YN0000: [parallel-workers]:
➤ YN0000: [parallel-workers]:
➤ YN0000: [parallel-workers]: > parallel-workers@1.0.0 build
➤ YN0000: [parallel-workers]: > webpack --config ./webpack.config.js "$@"
➤ YN0000: [parallel-workers]:
➤ YN0000: [parallel-workers]: Building for version : dev
➤ YN0000: [parallel-workers]: [webpack-cli] Failed to load 'C:\repos\accessibility-insights-service\packages\parallel-workers\$@' config
➤ YN0000: [parallel-workers]: [webpack-cli] Error: Cannot find module 'C:\repos\accessibility-insights-service\packages\parallel-workers\$@'
➤ YN0000: [parallel-workers]: Require stack:
➤ YN0000: [parallel-workers]: - C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js
➤ YN0000: [parallel-workers]: - C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\bootstrap.js
➤ YN0000: [parallel-workers]: - C:\repos\accessibility-insights-service\node_modules\webpack-cli\bin\cli.js
➤ YN0000: [parallel-workers]: - C:\repos\accessibility-insights-service\node_modules\webpack\bin\webpack.js
➤ YN0000: [parallel-workers]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
➤ YN0000: [parallel-workers]:     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
➤ YN0000: [parallel-workers]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
➤ YN0000: [parallel-workers]:     at require (node:internal/modules/cjs/helpers:103:18)
➤ YN0000: [parallel-workers]:     at WebpackCLI.tryRequireThenImport (C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js:244:16)
➤ YN0000: [parallel-workers]:     at loadConfigByPath (C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js:1712:30)
➤ YN0000: [parallel-workers]:     at C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js:1767:11
➤ YN0000: [parallel-workers]:     at Array.map (<anonymous>)
➤ YN0000: [parallel-workers]:     at WebpackCLI.loadConfig (C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js:1766:24)
➤ YN0000: [parallel-workers]:     at WebpackCLI.createCompiler (C:\repos\accessibility-insights-service\node_modules\webpack-cli\lib\webpack-cli.js:2187:29) {
➤ YN0000: [parallel-workers]:   code: 'MODULE_NOT_FOUND',
➤ YN0000: [parallel-workers]:   requireStack: [
➤ YN0000: [parallel-workers]:     'C:\\repos\\accessibility-insights-service\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
➤ YN0000: [parallel-workers]:     'C:\\repos\\accessibility-insights-service\\node_modules\\webpack-cli\\lib\\bootstrap.js',
➤ YN0000: [parallel-workers]:     'C:\\repos\\accessibility-insights-service\\node_modules\\webpack-cli\\bin\\cli.js',
➤ YN0000: [parallel-workers]:     'C:\\repos\\accessibility-insights-service\\node_modules\\webpack\\bin\\webpack.js'
➤ YN0000: [parallel-workers]:   ]
➤ YN0000: [parallel-workers]: }
➤ YN0000: [parallel-workers]: npm ERR! Lifecycle script `build` failed with error:
➤ YN0000: [parallel-workers]: npm ERR! Error: command failed
➤ YN0000: [parallel-workers]: npm ERR!   in workspace: parallel-workers@1.0.0
➤ YN0000: [parallel-workers]: npm ERR!   at location: C:\repos\accessibility-insights-service\packages\parallel-workers
➤ YN0000: [parallel-workers]: ERROR: "build" exited with 1.
➤ YN0000: [parallel-workers]: Process exited (exit code 1), completed in 2s 607ms
```
</details>

The operative line is `[webpack-cli] Failed to load
'C:\repos\accessibility-insights-service\packages\parallel-workers\$@'
config` - the webpack command was receiving a literal `$@`, instead of
the intended behavior of the package's `build` run-script receiving "the
rest" of its args as pass-through args.

In general, as of v2, yarn bundles its own minimal shell that is
intended to be able to interpret bash-like variables like the `\"#@\"`
used by this build script. However, #2009 included a workaround for a
lerna issue which involved adding `--npm-path npm` to every use of
`npm-run-all` in the repo, which causes `npm` to interpret sub-commands
instead of `yarn`, bypassing this behavior and instead using
host-specific shell intepretation, which is why we see an issue on
Windows but not Linux. This is commonly used in `cbuild` run-scripts to
run `clean` and `build` in serial.

Since we no longer use Lerna as of #2210, the workaround is no longer
necessary. This PR removes the workaround. I verified that this is
sufficient for `yarn cbuild` and `yarn precheckin` to work on a Windows
machine from both the `/packages/parallel-workers` directory and the
root directory (where the workaround was previously required).

##### Context

See #2009, #2210

#### Pull request checklist
<!-- If a checklist item is not applicable to this change, write "n/a"
in the checkbox -->

- [n/a] Addresses an existing issue: Fixes #0000
- [n/a] Added relevant unit test for your changes. (`yarn test`)
- [n/a] Verified code coverage for the changes made. Check coverage
report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)
- [n/a] Validated in an Azure resource group